accelerator:
  device: "cuda"

path:
  offline_data_path: "./data/offline"
  smooth_data_path: ".b/data/smooth"
  rotation_data_path: "./data/rotation"
  cluster_data_path: "./data/clustering"

model:
  model_name: "deepseek-ai/DeepSeek-V2-Lite"
  model_params: "eager"

calibration:
  dataset_name: "Self-GRIT/wikitext-2-raw-v1-preprocessed"

common_setting:
  weight_group_size: -1
  input_group_size: -1
  cluster_num: 16
  activation_quantization_bit: 4

cluster:
  max_sample: 512
  batch_size: 32
  max_length: 256
  epochs: 4
  fine_tune_lr: 0.001
  permutation: False

rotation:
  is_R2: False
  max_sample: 1024
  batch_size: 32
  max_length: 256
  epochs: 16
  fine_tune_lr: 0.0001

eval:
  activation_quantization_bit: 4
  weight_quantization_bit: 4
  tasks: "piqa,hellaswag,arc_easy,arc_challenge,mmlu,winogrande"
  ppls: "allenai/c4,Self-GRIT/wikitext-2-raw-v1-preprocessed"